services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data_processing/:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    restart: unless-stopped

  # weaviate:
  #   command:
  #     - --host
  #     - 0.0.0.0
  #     - --port
  #     - '8080'
  #     - --scheme
  #     - http
  #   image: cr.weaviate.io/semitechnologies/weaviate:1.18.4
  #   ports:
  #     - "8080:8080"
  #     - "50051:50051"
  #   volumes:
  #     - weaviate_data:/var/lib/weaviate
  #   restart: on-failure:0
  #   environment:
  #     QUERY_DEFAULTS_LIMIT: 25
  #     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
  #     PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
  #     ENABLE_API_BASED_MODULES: 'true'
  #     CLUSTER_HOSTNAME: 'node1'

  qdrant:
     image: qdrant/qdrant
     ports:
       - "6333:6333"
       - "6334:6334"
     volumes:
       - qdrant_data:/qdrant/storage
     restart: unless-stopped

  langflow:
    build:
      context: .
      dockerfile: Dockerfile.langflow
    ports:
      - "7860:7860"
    user: user
    environment:
      LANGFLOW_PORT: 7860
    depends_on:
      - qdrant
    restart: unless-stopped
    # volumes:
    #   - ./langflow_db/langflow.db:/app/.venv/lib/python3.12/site-packages/langflow/langflow.db

volumes:
  # weaviate_data:
  # langflow_data:
  qdrant_data:
