services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data_processing/:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    restart: unless-stopped
